name: Update Lua Submodule

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update_lua_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update Lua submodule
        run: |
          git submodule update --remote --merge

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1

      - name: Configure and build with CMake
        run: |
          # Check for submodule changes
          if git submodule status --recursive | grep -q '^+'; then
              git submodule update --init --recursive --progress
          fi

          ls
          mkdir build && cd build
          cmake ..
          cmake --build .

      - name: Commit and push changes
        run: |
          # Check for changes in the repository
          if git diff-index --quiet HEAD --; then
              echo "No changes in the repository."
          else
              # Commit the changes, including submodule updates
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git commit -am "Update Lua submodule and other changes"
              git push
          fi
